groups:
  - name: service-alerts
    rules:
      - alert: HighErrorRate
        expr: increase(app_requests_total{status="500"}[1m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on service"
          description: "More than 5 errors in the last minute"
